### PR TITLE
Fix double base64 encoding.

### LINKED ISSUE #13: Keys in secret are getting double base64 encoded
Take a look at `username`: `WVcxaFpHMXBiZz09` -> `YW1hZG1pbg==` -> `amadmin`

```
apiVersion: v1
Metadata:
  name: am-runtime
  namespace: default
data:
  keypass: WkhodWNGSjVaR3BaU0hwRVQyOHdUQT09
  username: WVcxaFpHMXBiZz09
kind: Secret

```

Steps to reproduce: 
1. start minikube
1.  `make install`
1. `make run`
1. `kubectl create config/samples`
1. see generated secrets

### PR DESCRIPTION
**Pull request by jrcast**
1. Fixes #13 : Secret data was getting double base64 encoded
1. Added info logs when creating/updating secrets.

### CODE REVIEW

File: controllers/secretagentconfiguration_controller.go [hunk 1]
```diff
@@ -120,22 +121,29 @@ func (reconciler *SecretAgentConfigurationReconciler) Reconcile(req ctrl.Request
...
-
 	labelsForSecretAgent := func(name string) map[string]string {
 		return map[string]string{"managed-by-secret-agent": "true", "secret-agent-configuration-name": name}
 	}
 
 	if instance.Spec.AppConfig.CreateKubernetesObjects {
-		for _, secret := range k8sSecretList {
-			// Set SecretAgentConfiguration instance as the owner and controller of the secret
-			if err := ctrl.SetControllerReference(&instance, secret, reconciler.Scheme); err != nil {
+		var operation *string
```
Comment (maxres-fr) [inline controllers/secretagentconfiguration_controller.go:129]: do we really need a pointer to a string here?

File: pkg/k8ssecrets/k8ssecrets_test.go [hunk 2]
```diff
@@ -110,20 +110,22 @@ func TestApplySecrets(t *testing.T) {
...
 	scheme := runtime.NewScheme()
 	clientgoscheme.AddToScheme(scheme)
-	client := fake.NewFakeClientWithScheme(scheme)
-	err := ApplySecrets(client, k8sSecrets)
-	if err != nil {
+	client := fake.NewFakeClientWithScheme(scheme, k8sSecret2)
+	//k8sSecret1 should be created, k8sSecret2 should be updated
+	k8sSecret2.Data = map[string][]byte{"otherkey": []byte(`YWRtaW4=`)}
+	k8sSecrets := []*corev1.Secret{k8sSecret1, k8sSecret2}
+	if _, err := ApplySecrets(client, k8sSecret1); err != nil {
```
Comment (maxres-fr) [inline pkg/k8ssecrets/k8ssecrets_test.go:123]: if we have to add many more sections like this we should use a "test table".

File: controllers/secretagentconfiguration_controller.go (hunk 1 above)
Comment (jrcast) [reply controllers/secretagentconfiguration_controller.go:129]: I think is nicer to compare against nil. i.e. `if operation != nil {`
rather than `if len(operation) > 0 {` if I were to return a string 🤷

Comment (jrcast) [reply controllers/secretagentconfiguration_controller.go]: changed to string
